replicaCount: 1

image:
  repository: ghcr.io/saravana-kr22/cortexos/auth-service
  pullPolicy: IfNotPresent
  tag: "sha-c0a8a1f"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8000

config:
  environment: "development"
  logLevel: "INFO"

secrets: {}
  # Example
  # JWT_SECRET: "my-secret-key"
  # DATABASE_URL: "postgres://user:pass@db:5432/dbname"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
