replicaCount: 1

image:
  repository: ghcr.io/saravana-kr22/korobos/database-service
  pullPolicy: IfNotPresent
  tag: "sha-59080ef"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8000

config:
  environment: "development"
  logLevel: "INFO"

secrets: {}
  # Example
  # DATABASE_URL: "postgres://user:pass@db:5432/dbname"
  # REDIS_URL: "redis://redis:6379/0"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
